### ISSUE TITLE
Font too small and cache too short

### ISSUE THREAD

**Issue by Vchen47** [MotazSabri/Hanami-release#16] opened 2024-04-20 17:28 UTC
This software is really helpful for learning Spanish through watching Spanish movies which has no subtitles. However, there are a few aspects that I find inconvenient. Firstly, I wish there was an option to adjust the window size and font display, as the current settings make it difficult for me to watch the small window and fonts without missing important information. Secondly, when I need to view translated content, it often disappears after a few seconds. It would be great if the transcribed content could remain visible for at least few minute, giving me more time to analyze the content. I hope the development team can address these issues and improve the software.

**Comment by MotazSabri** [comment] 2024-05-01 07:22
Thank you for utilizing Hanami for your language learning endeavors, @Vchen47 . I am pleased to learn that the software has proven beneficial not only for meetings and media comprehension but also for enhancing language acquisition through Spanish movie immersion.

It is important to note that Hanami is designed to function as a compact extension alongside any played media, be it streaming content, recorded audio, or movies. As such, the size of the window is deliberately set to maintain non-intrusiveness and ensure optimal readability within its compact framework. The font size is dynamically configured to accommodate content without sacrificing legibility, catering to the inherent constraints of its size. Sadly, it is hard to break this criteria as the application does not allow resizing like other windows apps.

In addressing your concerns regarding the transient nature of translated content, Hanami offers a solution through its navigation interface located at the bottom of the application. This feature allows users to revisit previously displayed translations by employing intuitive navigation buttons, including "Go to first," "Go one step backward," "Pause," "Go one step forward," and "Go to the latest translation." Utilizing these navigation controls facilitates seamless access to missed content without disrupting the translation process. It is noteworthy that engaging with the navigation feature automatically halts translation updates until the user opts to resume playback.

I appreciate your feedback and remain committed to refining Hanami to meet the evolving needs of its users. Should you have any further suggestions or queries, please do not hesitate to reach out to our development team.

**Comment by Vchen47** [comment] 2024-05-01 07:32
hello Motaz，
Thank you so much for your reply. I am happy Hanami still hs a strong team
supporting.
As for the review to transcibed content, i know there are set of buttons.
The issue is after a while, i mean not more than 10 seconds, the contents
are totally lost. I believe  it is your application on purposely to clean
the cache to keep availability for new coming audio input. if it possible
to maintain all the most recent contents if there is no new audio injected?
In this way i can learn or copy the content in a not hurry way.

Again thank you!

Regards,

Vchen



Motaz Sabri ***@***.***> 于 2024年5月1日周三 09:22写道：

**Comment by MotazSabri** [comment] 2024-05-01 08:34
Thanks for your detailed response and support. @Vchen47 
You referred to an issue that happens after 10 seconds where the previous translations are no longer available. The app keeps track for all the translated text as this will help in the text summarization and content analysis. I made a test and i am attaching it to this post for your reference.

For one minute of live translation (For an academic paper), the app managed to keep track of all translations, allowed user to navigate to all content to read thoroughly while keeping the live translation on. User continued operating the app to read live content at the end.

https://github.com/MotazSabri/Hanami-release/assets/72955854/8b9d6cf5-e792-4663-92eb-c4c331c41fc1

Sorry if the text is self explanatory, but are you experiencing different behavior?

**Comment by Vchen47** [comment] 2024-05-01 14:18
Hello dear Motaz,

I just watch your tutorial. seems you can hold the content for very long
time, more than 15 seconds at least. even till the final in your video, the
content still exists.

But can you check my using case in my video:
https://youtu.be/JHZ1tOzCmWU

from 15" seconds, I paused the original video, then you can see that at the
26" seconds, the content was washed. I click any button of replay it is
empty and shows instead: "no audio input, have you picked an idle device".

maybe I missed something in setting. can I hold all content when I pause
original clip? 10 seconds is far not enough for me to learn all the
subtitles.

Regards,
Vchen47




Motaz Sabri ***@***.***> 於 2024年5月1日 週三 下午4:34寫道：

**Comment by MotazSabri** [comment] 2024-05-02 01:41
Thank you for the detailed explanation and visuals, @Vchen47 . I now understand your perspective.

Regarding the idle state operation, it activates when the user pauses their input source or switches to a speaker without any audio signal. This triggers a yellow then red marker next to the speaker names combo box, accompanied by a message indicating the idle state to the user. This is crucial for informing the user that their selected source has no audio signal. During this mode, transcription and translation operations are paused, but navigation operations continue uninterrupted. Users can still navigate across all translations registered since the beginning of operations.

I observed that you clicked on the navigation only once when the idle state message appeared, which might have overwritten your command. All navigation buttons remain enabled during the idle state, and you can use them freely. I'm attaching a video for your reference.

https://github.com/MotazSabri/Hanami-release/assets/72955854/eb1fe236-cf97-4462-afd0-8bce84830fa9

Therefore i think you may still use the navigation options freely. I hope this answers your concerns.

**Comment by Vchen47** [comment] 2024-05-02 16:27
Thank you Motaz,
For you still work in Worker's day.

What I encounter in my desk is that: when there is no audio detected, I can
browse 10 seconds by the navigation buttons. But after 10 seconds, there
just stick to showing "no Audio signal, have you picked an idle device?".
the navigation button no function at all. it looks like the cache has been
cleaned total. But then when I resume the audio replay, to my suprise, the
window start to show again the translation/transcribe and when I click
navigation all caches recovered back . indeed, the cache didnot clean
nothing.

My question is how can I keep the ability to navigate, without be stucked
by showing the "no Audio signal, have you picked an idle device?" in idle
stage. because when I learn language, I need to stop the video/audio and
recheck the cache to analysis the subtitle line by line. I can not navigate
when Video/audio still ongoing. If you have the solution, that would be
fantastic!

Regards,
Vchen

Motaz Sabri ***@***.***> 於 2024年5月2日 週四 上午9:41寫道：

**Comment by MotazSabri** [comment] 2024-05-04 08:15
My pleasure.

It is a relief to know the cache is still reachable at your side after resuming the audio. It's normal to pause the source and navigate through the processed texts. 

I tried the same flow you kindly mentioned at few other machines (multiple windows version) and the stuck behavior you are referring to did not happen.

Does the entire app stuck/freeze after the Idle message appear? Or is it only the navigation buttons that won't function? According to the video you shared, seems the application is still responsive (buttons hover effect is visible).

The navigation logic is separated from the translation logic. Therefore the application flow shouldn't prevent the text navigation if the audio source stops. Maybe you can try running the app as an admin or reinstall it again.

Also try to check the app logs:

1. Go to the Windows TEMP folder (By clicking WINDOWS + R and then type %temp% and enter) and find a folder called HanamiApp.
2. The file contains the operational contents, delete everything in it (To avoid sharing any personal details) then run the Hanami application.
3. After a while of running the app (Seconds), in the HanamiApp folder, you will find a file called Traces.log. In it, we may find clues as to why this issue happened.
4. If it's a thing you can not manage by yourself, please share the traces.log here so I can try debugging it.

**Comment by Vchen47** [comment] 2024-05-05 18:23
Hello Motaz,

indeed the application still running when I click any button of navigation
when Video is idle. I can see that the buttons were pushed down and popup
each.

I am very curious that you didnot meet this issue in your desk. maybe it is
a cache confiliction in my desk that happened between Hanami and other
applications but I dont know.

As you guide to search the log file, unfortunately, I see that the folder
of HanamiApp is empty.  if there is a trigger to provoke log please let me
know. if not, maybe my version downloading from GITHUB is not the same as
yours. my verision is released at Feb.15th.

Regards,
Vchen47

Motaz Sabri ***@***.***> 於 2024年5月4日 週六 下午4:15寫道：

**Comment by MotazSabri** [comment] 2024-05-07 02:48
Thank you for your attention to this matter, @Vchen47 . The previous version of the logger only recorded exceptions and errors if they occurred. I have now provided a temporary version of the application that logs all activities for testing purposes. However, please note that this version operates notably slower. [This link](https://github.com/MotazSabri/Hanami-release/releases/download/Hanami-release1.9/HanamiGUI.zip) to access this temporary version will be removed once the identified issue is confirmed, to prevent confusion among users.

To replicate the behavior you mentioned, please follow these steps:
1. Utilize the application to translate content.
2. Pause the source stream.
3. Wait until the idle message is displayed.
4. Utilize the text navigators.

After completing these steps, review the logs. I have included an example of what the logs may resemble when utilizing the "Next" translation feature. Upon clicking the "Next translation" button ">", the application's logger will promptly display the index of the retrieved translation, indicating that the designated translation is being presented. If you observe a similar segment in your logs, situated between the "**User requested to navigate to next subs**" and "**Subs of index XXX is shown to user.**" markers, it indicates that the application is functioning correctly. This also suggests that any issues encountered may be occurring beyond the application's control.



**2024-05-07 09:24:05,437 init - INFO:User requested to navigate to next subs**
2024-05-07 09:24:05,441 init - INFO: --- Finished the listening tread.
2024-05-07 09:24:05,448 init - INFO:New chunk is being processed, Listening ... 
2024-05-07 09:24:05,449 init - INFO: --- Started the listenng thread.
2024-05-07 09:24:05,449 init - INFO: --- Transducing starting.
2024-05-07 09:24:05,449 init - INFO: --- Started the translation thread.
2024-05-07 09:24:05,450 init - INFO: --- Finished the listening tread.
2024-05-07 09:24:05,450 init - INFO:New chunk is being processed, Listening ... 
2024-05-07 09:24:05,450 init - INFO: --- Started the listenng thread.
2024-05-07 09:24:05,450 init - INFO: --- Transducing starting.
2024-05-07 09:24:05,450 init - INFO: --- Started the translation thread.
2024-05-07 09:24:05,451 init - INFO: --- Finished the listening tread.
2024-05-07 09:24:05,451 init - INFO:New chunk is being processed, Listening ... 
2024-05-07 09:24:05,451 init - INFO: --- Started the listenng thread.
2024-05-07 09:24:05,451 init - INFO: --- Transducing starting.
2024-05-07 09:24:05,451 init - INFO: --- Started the translation thread.
2024-05-07 09:24:05,452 init - INFO: --- Finished the listening tread.
2024-05-07 09:24:05,452 init - INFO:New chunk is being processed, Listening ... 
2024-05-07 09:24:05,452 init - INFO: --- Started the listenng thread.
2024-05-07 09:24:05,452 init - INFO: --- Transducing starting.
2024-05-07 09:24:05,452 init - INFO: --- Started the translation thread.
2024-05-07 09:24:05,453 init - INFO: --- Finished the listening tread.
2024-05-07 09:24:05,453 init - INFO:New chunk is being processed, Listening ... 
2024-05-07 09:24:05,453 init - INFO: --- Started the listenng thread.
2024-05-07 09:24:05,453 init - INFO: --- Transducing starting.
2024-05-07 09:24:05,454 init - INFO: --- Started the translation thread.
**2024-05-07 09:24:05,454 init - INFO:Subs of index 4 is shown to user.**

I welcome your thoughts and feedback regarding this matter.

**Comment by Vchen47** [comment] 2024-05-07 14:03
Hello Motaz,
Thank you for your consistent attention. I am glad to help you figuring out
this issue. I have run the debug-App. and recorded the log. here is the log
that corresponding why I click the navigation bar during the idle stage it
doesnot show the cache.

2024-05-07 21:55:18,905 init - INFO: --- Started the listenng thread.
2024-05-07 21:55:18,905 init - INFO:No audio signal. Have you picked an
idle device
2024-05-07 21:55:18,906 init - INFO: --- Transducing starting.
2024-05-07 21:55:18,906 init - INFO: --- Started the translation thread.
2024-05-07 21:55:18,906 init - INFO: --- Finished the listening tread.
2024-05-07 21:55:18,906 init - INFO:New chunk is being processed, Listening
...
2024-05-07 21:55:18,906 init - INFO: --- Started the listenng thread.
2024-05-07 21:55:18,907 init - INFO:Hanami shutting down
2024-05-07 21:55:18,909 init - INFO:Clearing all drivers and browsers
instances
2024-05-07 21:55:18,914 init - INFO:Stopping Hanami core
2024-05-07 21:55:18,914 init - INFO:No Audio signal detected
2024-05-07 21:55:18,914 init - INFO:Done with recording
2024-05-07 21:55:18,915 init - INFO:No Audio signal detected
2024-05-07 21:55:22,479 init - CRITICAL:Unable to access process
2024-05-07 21:55:22,480 init - CRITICAL:Unable to access process
2024-05-07 21:55:22,482 init - CRITICAL:Unable to access process
2024-05-07 21:55:22,483 init - CRITICAL:Unable to access process
2024-05-07 21:55:22,485 init - CRITICAL:Unable to access process
2024-05-07 21:55:22,486 init - CRITICAL:Unable to access process
2024-05-07 21:55:22,488 init - CRITICAL:Unable to access process
2024-05-07 21:55:22,489 init - CRITICAL:Unable to access process
2024-05-07 21:55:22,577 init - CRITICAL:Unable to access process
2024-05-07 21:55:22,606 init - CRITICAL:Unable to access process
2024-05-07 21:55:22,627 init - CRITICAL:Unable to access process
2024-05-07 21:55:22,629 init - CRITICAL:Unable to access process
2024-05-07 21:55:22,671 init - CRITICAL:Unable to access process

And I attatched the whole log. I small wish, since i notice that you are
keep maintaining this application, would you think to make the font be much
bigger? I do think it is not consume any memory or CPU capacity. and in the
window, if you can show at least 2 lines in same window that will be useful
for language learner to understand whole context. do you agree?

Regards,
vchen

Motaz Sabri ***@***.***> 於 2024年5月7日 週二 上午10:48寫道：

**Comment by MotazSabri** [comment] 2024-05-07 23:47
Thanks for following up, @Vchen47 . I've reviewed the logs section  you shared, but I couldn't find any navigation clicking events, like "User requested to navigate to ...", which should be visible at least. 

If these events aren't visible, it's possible that the left cursor click isn't reaching the application, possibly due to another application blocking it or shadowing it. Could you please try using the left cursor button on all navigation buttons while the application is in an idle state? If there's no response in the app or in the logs, we might need to investigate beyond the app's boundaries.

Regarding the font size, since it's currently favored by other users, it's difficult to change it based on individual preferences. However, in future releases, I can consider adding a config file that allows users to customize the application's behavior.

When you mention "showing two lines," do you mean displaying the previous translation in one line and the current translation in another, or do you mean showing the original text in one line and the translation in another? The latter feature was actually added in the last release as the "Mixture" feature.

P.S. The log message "CRITICAL: Unable to access process" indicates that the application is attempting to shut down and close all sub-applications within the process.

**Comment by Vchen47** [comment] 2024-05-09 07:49
Hello Motaz,

I am 100% sure left cursor button was correctly pushed, because i can see
the navigation buuton is appearing being pushed down.

For two lines i mean the first understanding. To contain two lines of
transcribe.


For the final critical issue i will see if this is because i am shutting
down the app. Maybe i should fetch the log before shutdown it. Anyway seems
the log doesnot reflect the issue that i am encountering.

Thank you!

Vchen




Motaz Sabri ***@***.***> 于 2024年5月8日周三 01:47写道：

**Comment by MotazSabri** [comment] 2024-05-09 14:21
Thank you for your prompt response and confirmation, @Vchen47 .

I've tailored a custom build to tackle the issues you highlighted. This version enables two-line translation (for both previous and current text) and grants users the ability to adjust font size and window size. Since the app doesn't inherently support resizing, please exercise caution when modifying settings. You can access the temporary build via this [URL](https://github.com/MotazSabri/Hanami-release/releases/download/Hanami-release1.9/HanamiGUI.zip), which will be removed once you've downloaded it, as it includes specific features you requested.

I've preset the values for increased height and larger font. To adjust to your preferences, locate the following section in the Interface_structure.json file (in HanamiGUI\Assets directory):

```json
"app": {
    "translationFont" : 14,
    "sample_rate": 8000,
    "Compact": {
        "w": 545,
        "h": 250
      },
    "Extended": {
        "w": 545,
        "h": 300
      }
}
```

Here, you can set the font size using `translationFont`, and adjust the application height by modifying the `h` value in both compact and extended modes. Original `translationFont`value was 12 while the extended `h` was 200 and the compact `h` was 150.

I trust these modifications align with your requirements for the application. Please don't hesitate to reach out with further feedback or close this issue if everything meets your expectations.

**Comment by Vchen47** [comment] 2024-05-09 21:02
Hello, Motaz,

So much thank you! you have a great spirit at what you are doing.

I have tried this trial version and I feel this is a fantastic for my
usage. I can see big font and I have two line remind me the anterior
contexts. great and thanks again!

I'm looking for a programming expert who can lead two students to
collaborate on developing an app for piano theory and playing instruction,
based on mobile devices. Not sure if you're interested. If you are, we can
discuss further. However, I also understand that your interests lie in the
specialized field of AI and this is a big dream. So, if you're not
interested or don't have the time, that's okay too.

Regards,

Vchen47

Motaz Sabri ***@***.***> 於 2024年5月9日 週四 下午10:21寫道：

**Comment by MotazSabri** [comment] 2024-05-10 08:38
Thank you for confirming, and I appreciate your patience in addressing your concerns, @Vchen47 .

If everything meets your satisfaction, please feel free to close the issue. The temporary version URL will be removed shortly.

Regarding your generous offer, I must express my gratitude for considering me. However, at present, my schedule is quite occupied with existing commitments, and regrettably, I cannot fully dedicate myself to leading the team. Nonetheless, I value the trust you've placed in me.

**Comment by MotazSabri** [comment] 2024-06-05 00:19
@Vchen47 

I hope the new version (Hanami 2.0) meets your expectations.
For your reference, I have attached the Interface_structure.json file, which controls the layout (application width, font size, etc.) for the custom version I previously shared.

[Interface_structure.json](https://github.com/user-attachments/files/15571541/Interface_structure.json)
You may overwrite your existing Interface_structure.json file in your Assets folder (HanamiGUI\Assets directory)
The file includes the following changes:

```
"app": {
    "sub_translationFont": 12,  // Smaller font size for previous translation text
    "translationFont": 13,      // Main translation font size
    "gpt_font": 12,             // GPT window font size
    "default_src_language": "Japanese ☆",
    "default_tgt_language": "English ☆",
    "sample_rate": 8000,
    "Compact": {
        "w": 545,
        "h": 285                // Application height when the top controls are not visible
    },
    "Extended": {
        "w": 545,
        "h": 305                // Application height when the top controls are visible
    }
},
"GPT_window": {
    "Extended": {
        "w": 321,               // GPT window width regardless of application control visibility
        "h": 500                // GPT window height regardless of application control visibility
    }
}
```

Thanks for your remarks.

**Closed by MotazSabri** 2024-06-05 00:19 UTC

**Comment by Vchen47** [comment] 2024-06-05 21:38
Hi, Motaz

I just realize you have updated. but in the Github release page, you still
not update yet:
[image: image.png]

I've tried the new version(2.0) of Hanami, and I can say it’s more helpful
for real translators. In this new version, we could download and save
content anytime, and now, an interesting feature (Contrans) shows two lines
simultaneously and you enlarge the most current sentence. This sets you
apart from other apps in the market.

I have no further suggestions. Perhaps you could make the main frame of the
app much bigger, why not a full window, and enlarge the font size so
listeners can see the text even from a distance. This would encourage the
app’s use in real scenarios like international conferences.

To make it more useful, I'd suggest that the speed of speech content
recognition depends on the model you're using. Currently, you use the free
version of GPT, for my language learing is acceptable. but for commercial
users might bit too slow. always latency at 4 seconds or more. I prefer
faster AI models like GPT-4o. I’ve heard GPT-4o is several times faster
than GPT-3.5. I’ve tried it in chat text interaction, but I'm not sure if
it significantly enhances speech recognition speed. It would be great if
you allowed users to input their own OpenAI API key for GPT-4 if it really
works.

Thanks again!
Chen

Motaz Sabri ***@***.***> 於 2024年6月5日 週三 上午8:19寫道：

**Comment by MotazSabri** [comment] 2024-06-06 03:15
Hi @Vchen47,

Thank you for your kind message. I couldn’t see your picture, but I’ve updated the GitHub release page and the main page to reflect the changes. I hope these updates are accessible globally.

Currently, the app functions more as an extension or plugin rather than a full-window application. However, based on your request, some customization options are available, including setting the app size and font enlargement. I hope these adjustments meet your needs.

To clarify, the GPT model is only used for the "talking with your data" feature, which is the latest addition to the Hanami Family. The transcription and translation features use other classical models that are not GPT-based.

I understand that speed is an issue, and I am investigating a solution. One straightforward approach is to switch to a paid backend for transcription, which would also improve accuracy in handling high-noise audio. Would you consider paying for such an enhancement?

Thank you!

**Comment by Vchen47** [comment] 2024-06-08 11:41
Hello Motaz,

sure I will pay for it. the best way is your app fix the API, and user to
pay with a new model like pay as use model.

Chen

Motaz Sabri ***@***.***> 於 2024年6月6日 週四 上午11:15寫道：

**Comment by MotazSabri** [comment] 2024-07-08 05:26
For your reference, the layout can now be edited through the newly added control panel, accessible via the top bar (latest version).

More details can be found in the [main page](https://github.com/MotazSabri/Hanami-release).
![image](https://github.com/MotazSabri/Hanami-release/assets/72955854/f1b85f46-a301-47a6-bd35-2890fd8e169b)

**Comment by Vchen47** [comment] 2024-07-09 17:36
Thank you Motaz,
I have downloaded and on this new version. Very good!

Motaz Sabri ***@***.***> 於 2024年7月8日 週一 下午1:27寫道：
